---
title: "Exercício 1"
author: "Anderson Thelles"
date: "Sunday, October 19, 2014"
output: html_document
---

**Exercício 1:**

O vídeo mostra de forma visual alguns gráficos para demonstrar os dados coletados dos anos 1960 até entre 2003 e 2015. Ele consegue, dessa maneira, fazer que o publico consiga perceber de forma instantanea, como os dados estão se comportando, com o passar dos anos, a partir de seu deslocamento e aceleração. Para facilitar essa visualização ele usa alguns atributos, como:

COR: Cada continente tem uma cor em específico.
TAMANHO: Cada ponto tem um tamanho diferente que define a população do país ou continente.
VELOCIDADE: Ele pode dar merge em todos os gráficos do inicial ao final e a partir disso, podemos ver se um dos pontos estão se afastando rapidamente ou não.

Com esses dados, ele consegue perceber facilmente qual o comportamento eles estão tendo com o passar do tempo, nas tabelas:

- Crianças por mulheres adultas
- Mortalidade infantil por renda
- População por Salário Diário

Baseado nessas comparações de tabelas, ele tenta mostrar os paises mais desenvolvidos.

**Exercício 2:**

Olhando os dados podemos perceber que mais de 50% trabalham 8 horas por dia nos diversos estados, mas mesmo assim, a faixa de salário deles são bem variados, dos 42.120 para o mais alto e de 500 no mínimo, onde 50% ganham entre 2.281 à 5.332, com uma média de 4.233 e mediana 3.583, podemos concluir que tem valores mais extremos que ganham muito acima da média ou abaixo dela, trabalhando a mesma quantidade de horas.

Podemos perceber que quanto mais baixo o seu salário, o indice de escolaridade (se é pós-graduado ou se tem uma certificação) vai ficando cada vez mais baixo, ou seja, poucos que tem pós-graduação consegue ter salários altos.

**Exercício 3:**

O boxplot mostra que alguns salários estão muito acima da média, chegando à mais de 40000. De forma mais fácil de visualisar, ao vermos o histórico podemos ver que a frequência de pessoas que recebem acima de 10000 é minusculo.

**Exercício 4**

Apenas com a média de horas diárias de trabalho, imaginava uma faixa salárial parecido, mas não foi exatamente isso que aconteceu. Como visto antes na questão 2, Um dos fatores que provavelmente afetou o salário foi a escolaridade.

**Exercício 5**

Se eu tivesse usado a mediana, poderia ter algumas conclusões mais concretas já que alguns pontos são muito alto comparado com a maioria. A média nesses casos são aumentados de forma enorme por causa desses pontos, como por exemplo no nordeste, que a média tem uma variação de 1666 entre a média e mediana.

**Exercício 6**

Pelo que foi percebido, o local que tem a maior mediana de salário é no centro-oeste, então nesse local ele provavelmente irá ganhar um salário bom. Para garantir ainda mais sucesso, ele poderia ter uma pós-graduação. Boa parte dos pós-graduados tem salários maior que a as outras pessoas não graduadas.
